name: 运行马蹄小莲机器人

on:
  schedule:
    # 每15分钟运行一次（UTC时间）
    - cron: "*/15 * * * *"
  workflow_dispatch:  # 允许手动运行

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: 安装依赖
        run: pip install requests
        
      - name: 运行机器人
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
          DEEPSEEK_KEY: ${{ secrets.DEEPSEEK_KEY }}
        run: python bot.py | tee bot.log  # 保存日志到文件
        
      - name: 上传日志
        if: always()
        uses: actions/upload-artifact@v4  # 使用 v4 版本
        with:
          name: bot-logs
          path: bot.log
          retention-days: 1  # 只保留1天日志
