name: 终极版马蹄小莲机器人

on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟运行一次（更可靠）
  workflow_dispatch:     # 允许手动触发

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 2   # 给予足够时间
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3
          pip install requests
      
      - name: 创建初始数据库
        run: |
          if [ ! -f bot_state.db ]; then
            sqlite3 bot_state.db "CREATE TABLE bot_state (key TEXT PRIMARY KEY, value TEXT);"
            sqlite3 bot_state.db "CREATE TABLE processed_messages (message_hash TEXT PRIMARY KEY, processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"
            echo "创建初始数据库"
          else
            echo "数据库已存在"
          fi
      
      - name: 运行机器人
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
          DEEPSEEK_KEY: ${{ secrets.DEEPSEEK_KEY }}
        run: python bot.py
        
      - name: 保存数据库
        uses: actions/upload-artifact@v4
        with:
          name: bot-database
          path: bot_state.db
          retention-days: 30
      
      - name: 恢复数据库
        uses: actions/download-artifact@v4
        with:
          name: bot-database
          path: .
