name: 超高速马蹄小莲机器人

on:
  schedule:
    - cron: "* * * * *"  # 每分钟运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 1   # 严格限制1分钟超时

       steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
               - name: 安装依赖
        run: pip install requests
      
      - name: 运行机器人
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
          DEEPSEEK_KEY: ${{ secrets.DEEPSEEK_KEY }}

          run: python -c "import os; from datetime import datetime,  timezone; print('启动时间:', datetime.now(timezone.utc).isoformat())" && python bot.py
